import { Metadata } from "next";
import HeadingPage from "@/components/HeadingPage/HeadingPage";

export const metadata: Metadata = {
  title: "Legal Notice - EyeChallenge",
  description: "Legal information, terms of use, and privacy policy for the EyeChallenge website.",
};

export default function LegalPage() {
  return (
    <section className="py-10 sm:py-18 main-container flex flex-col items-center">
      <HeadingPage
        title="Legal Notice"
        description="Legal information and terms of use for EyeChallenge."
      />
      <div className="prose max-w-4xl mx-auto">
        <p className="mb-4">
          In accordance with the provisions of the law for confidence in the digital economy, users of the EyeChallenge website are informed of the identity of the various parties involved in its creation and monitoring.
        </p>

        <h2 className="mb-2">1. Site Edition</h2>
        <p className="mb-4">
          This site, accessible at the URL <code>https://www.eyechallenge.fun</code>, is published by:
          <br />
          <strong>Franklin Hyriol</strong>, individual entrepreneur.
          <br />
          <strong>Email:</strong> franklinrazafy@gmail.com
          <br />
          <a href="https://www.linkedin.com/in/franklin-hyriol-razafinandrasana-4b9a71217/" target="_blank" rel="noopener noreferrer" className="text-primary font-bold">LinkedIn Profile</a>
        </p>
        <p className="mb-4"><em>(Note: If you are registered as a business, you should add your registration number and business address here.)</em></p>

        <h2 className="mb-2">2. Hosting</h2>
        <p className="mb-4">
          The site is hosted by the company <strong>Railway Corporation</strong>.
          <br />
          <strong>Address:</strong> 548 Market St PMB 68956, San Francisco, California 94104, United States.
          <br />
          <strong>Contact:</strong> team@railway.app
        </p>

        <h2 className="mb-2">3. Personal Data and Cookies</h2>
        <p className="mb-4">
          This site does not directly collect personal data (name, address, etc.) through registration or comment forms.
        </p>
        <p className="mb-4">
          However, the site uses <strong>Google Analytics</strong> for audience measurement purposes. Google Analytics uses "cookies," which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.
        </p>
        <p className="mb-4">
          You can disable the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website.
        </p>

        <h2 className="mb-2">4. Limitation of Liability</h2>
        <p className="mb-4">
          The information and tests offered on the EyeChallenge site are for entertainment and informational purposes only. They shall not, under any circumstances, constitute medical advice or a professional diagnosis. <strong>Franklin Hyriol</strong> cannot be held responsible for any direct or indirect damages that may result from accessing or using the site.
        </p>
      </div>
    </section>
  );
}
